# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'archiveframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArchivFrame(object):
    def setupUi(self, ArchivFrame):
        ArchivFrame.setObjectName("ArchivFrame")
        ArchivFrame.resize(514, 600)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ArchivFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 451, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.l_titelarchive = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_titelarchive.setStyleSheet("font-size: 15pt;")
        self.l_titelarchive.setAlignment(QtCore.Qt.AlignCenter)
        self.l_titelarchive.setObjectName("l_titelarchive")
        self.horizontalLayout_4.addWidget(self.l_titelarchive)
        self.l_icon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_icon.setStyleSheet("image: url(:/Images/logo_small_icon_only_inverted.png);")
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.horizontalLayout_4.addWidget(self.l_icon)
        self.t_archivelist = QtWidgets.QTableWidget(ArchivFrame)
        self.t_archivelist.setGeometry(QtCore.QRect(30, 180, 451, 281))
        self.t_archivelist.setObjectName("t_archivelist")
        self.t_archivelist.setColumnCount(0)
        self.t_archivelist.setRowCount(0)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(ArchivFrame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 120, 451, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.l_description = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.l_description.setObjectName("l_description")
        self.horizontalLayout_2.addWidget(self.l_description)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(ArchivFrame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 470, 451, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.b_back = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.b_back.setObjectName("b_back")
        self.horizontalLayout_3.addWidget(self.b_back)
        self.b_viewarchive = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_viewarchive.sizePolicy().hasHeightForWidth())
        self.b_viewarchive.setSizePolicy(sizePolicy)
        self.b_viewarchive.setObjectName("b_viewarchive")
        self.horizontalLayout_3.addWidget(self.b_viewarchive)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)

        self.retranslateUi(ArchivFrame)
        QtCore.QMetaObject.connectSlotsByName(ArchivFrame)

    def retranslateUi(self, ArchivFrame):
        _translate = QtCore.QCoreApplication.translate
        ArchivFrame.setWindowTitle(_translate("ArchivFrame", "Haushaltsplaner"))
        self.l_titelarchive.setText(_translate("ArchivFrame", "Archiv"))
        self.l_description.setText(_translate("ArchivFrame", "Archivierte Einkaufslisten"))
        self.b_back.setText(_translate("ArchivFrame", "Zurück"))
        self.b_viewarchive.setText(_translate("ArchivFrame", "Einkaufsliste ansehen"))
import menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ArchivFrame = QtWidgets.QWidget()
    ui = Ui_ArchivFrame()
    ui.setupUi(ArchivFrame)
    ArchivFrame.show()
    sys.exit(app.exec_())