# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'budgetplanerframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

monate = ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November",
          "Dezember"]


class Ui_Budgetplaner(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 637)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 921, 240))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_back.setStyleSheet("background-color: grey;\n"
"color: white;")
        self.b_back.setObjectName("b_back")
        self.horizontalLayout.addWidget(self.b_back)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.l_app = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_app.setStyleSheet("font-size: 15pt;")
        self.l_app.setAlignment(QtCore.Qt.AlignCenter)
        self.l_app.setObjectName("l_app")
        self.horizontalLayout.addWidget(self.l_app)
        spacerItem1 = QtWidgets.QSpacerItem(60, 60, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.l_icon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_icon.setStyleSheet("image: url(:/Images/logo_small_icon_only_inverted.png);")
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.horizontalLayout.addWidget(self.l_icon)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.b_day = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_day.setObjectName("b_day")
        self.horizontalLayout_5.addWidget(self.b_day)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.b_year = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_year.setObjectName("b_year")
        self.horizontalLayout_5.addWidget(self.b_year)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.b_previous = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_previous.setObjectName("b_previous")
        self.horizontalLayout_4.addWidget(self.b_previous)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.l_date = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_date.setAlignment(QtCore.Qt.AlignCenter)
        self.l_date.setObjectName("l_date")
        self.horizontalLayout_4.addWidget(self.l_date)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.b_next = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.b_next.setObjectName("b_next")
        self.horizontalLayout_4.addWidget(self.b_next)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.l_d = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_d.setObjectName("l_d")
        self.horizontalLayout_6.addWidget(self.l_d)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.l_s = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_s.setObjectName("l_s")
        self.horizontalLayout_6.addWidget(self.l_s)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.l_de = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.l_de.setObjectName("l_de")
        self.horizontalLayout_6.addWidget(self.l_de)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 540, 921, 75))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.b_edittransaction = QtWidgets.QPushButton(self.widget)
        self.b_edittransaction.setStyleSheet("background-color: grey;\n"
"color: white;")
        self.b_edittransaction.setObjectName("b_edittransaction")
        self.horizontalLayout_3.addWidget(self.b_edittransaction)
        self.b_addtransaction = QtWidgets.QPushButton(self.widget)
        self.b_addtransaction.setStyleSheet("background-color: orange;\n"
"color: white;")
        self.b_addtransaction.setObjectName("b_addtransaction")
        self.horizontalLayout_3.addWidget(self.b_addtransaction)
        self.b_deletetransaction = QtWidgets.QPushButton(self.widget)
        self.b_deletetransaction.setStyleSheet("background-color: grey;\n"
"color: white;")
        self.b_deletetransaction.setObjectName("b_deletetransaction")
        self.horizontalLayout_3.addWidget(self.b_deletetransaction)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 270, 921, 271))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem15 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)


        self.listofftransaction = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        self.listofftransaction.setStyleSheet("font-size:12pt;")
        self.listofftransaction.setObjectName("listofftransaction")
        self.horizontalLayout_2.addWidget(self.listofftransaction)

        self.listofftransaction.setColumnCount(3)
        self.listofftransaction.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.listofftransaction.verticalHeader().hide()
        self.listofftransaction.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listofftransaction.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)


        spacerItem16 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b_back.setText(_translate("Form", "Zurück"))
        self.l_app.setText(_translate("Form", "Budgetplaner"))
        self.b_day.setText(_translate("Form", "Tag"))
        self.pushButton_4.setText(_translate("Form", "Monat"))
        self.b_year.setText(_translate("Form", "Jahr"))
        self.b_previous.setText(_translate("Form", "<--"))
        self.l_date.setText(_translate("Form", monate[datetime.datetime.now().month -1] + str(2021)))
        self.b_next.setText(_translate("Form", "-->"))
        self.l_d.setText(_translate("Form", "Datum"))
        self.l_s.setText(_translate("Form", "Summe"))
        self.l_de.setText(_translate("Form", "Details"))
        self.b_edittransaction.setText(_translate("Form", "Buchung bearbeiten"))
        self.b_addtransaction.setText(_translate("Form", "Neue Buchung"))
        self.b_deletetransaction.setText(_translate("Form", "Buchung entfernen"))
import menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Budgetplaner()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
