# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructionframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Einkaufsplaner(object):
    def setupUi(self, Einkaufsplaner):
        Einkaufsplaner.setObjectName("Einkaufsplaner")
        Einkaufsplaner.resize(887, 726)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Einkaufsplaner)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 821, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.l_recipe = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_recipe.setStyleSheet("font-size: 15pt;")
        self.l_recipe.setAlignment(QtCore.Qt.AlignCenter)
        self.l_recipe.setObjectName("l_recipe")
        self.horizontalLayout_4.addWidget(self.l_recipe)
        self.l_icon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_icon.setStyleSheet("image: url(:/Images/logo_small_icon_only_inverted.png);")
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.horizontalLayout_4.addWidget(self.l_icon)
        self.t_incredientlist = QtWidgets.QTableWidget(Einkaufsplaner)
        self.t_incredientlist.setGeometry(QtCore.QRect(30, 370, 371, 201))
        self.t_incredientlist.setObjectName("t_incredientlist")
        self.t_incredientlist.setColumnCount(0)
        self.t_incredientlist.setRowCount(0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Einkaufsplaner)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 610, 821, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.b_back = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_back.setObjectName("b_back")
        self.horizontalLayout.addWidget(self.b_back)
        self.b_addrecipe = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_addrecipe.setObjectName("b_addrecipe")
        self.horizontalLayout.addWidget(self.b_addrecipe)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.list_instructions = QtWidgets.QListView(Einkaufsplaner)
        self.list_instructions.setGeometry(QtCore.QRect(440, 140, 411, 431))
        self.list_instructions.setObjectName("list_instructions")
        self.l_recipeimage = QtWidgets.QLabel(Einkaufsplaner)
        self.l_recipeimage.setGeometry(QtCore.QRect(30, 140, 371, 211))
        self.l_recipeimage.setAutoFillBackground(False)
        self.l_recipeimage.setStyleSheet("\n"
"image: url(:/Images/italienischer-zitronenkuchen.jpg);")
        self.l_recipeimage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l_recipeimage.setText("")
        self.l_recipeimage.setScaledContents(True)
        self.l_recipeimage.setWordWrap(False)
        self.l_recipeimage.setObjectName("l_recipeimage")

        self.retranslateUi(Einkaufsplaner)
        QtCore.QMetaObject.connectSlotsByName(Einkaufsplaner)

    def retranslateUi(self, Einkaufsplaner):
        _translate = QtCore.QCoreApplication.translate
        Einkaufsplaner.setWindowTitle(_translate("Einkaufsplaner", "Haushaltsplaner"))
        self.l_recipe.setText(_translate("Einkaufsplaner", "\"Rezeptname\""))
        self.b_back.setText(_translate("Einkaufsplaner", "Zurück"))
        self.b_addrecipe.setText(_translate("Einkaufsplaner", "Hinzufügen"))
import menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Einkaufsplaner = QtWidgets.QWidget()
    ui = Ui_Einkaufsplaner()
    ui.setupUi(Einkaufsplaner)
    Einkaufsplaner.show()
    sys.exit(app.exec_())
