# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructionframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rezeptanleitung(object):
    def setupUi(self, Rezeptanleitung):
        Rezeptanleitung.setObjectName("Rezeptanleitung")
        Rezeptanleitung.resize(887, 678)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Rezeptanleitung)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 811, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b_back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.b_back.setObjectName("b_back")
        self.horizontalLayout_4.addWidget(self.b_back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.l_recipe = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_recipe.setStyleSheet("font-size: 15pt;")
        self.l_recipe.setAlignment(QtCore.Qt.AlignCenter)
        self.l_recipe.setObjectName("l_recipe")
        self.horizontalLayout_4.addWidget(self.l_recipe)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.l_icon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_icon.setStyleSheet("image: url(:/Images/logo_small_icon_only_inverted.png);")
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.horizontalLayout_4.addWidget(self.l_icon)
        self.t_incredientlist = QtWidgets.QTableWidget(Rezeptanleitung)
        self.t_incredientlist.setGeometry(QtCore.QRect(40, 370, 371, 211))
        self.t_incredientlist.setObjectName("t_incredientlist")
        self.t_incredientlist.setColumnCount(2)

        header = self.t_incredientlist.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.hide()
        self.t_incredientlist.verticalHeader().hide()

        self.list_instructions = QtWidgets.QListWidget(Rezeptanleitung)
        self.list_instructions.setGeometry(QtCore.QRect(440, 140, 411, 441))
        self.list_instructions.setObjectName("list_instructions")

        self.list_instructions.setWordWrap(True)

        self.l_recipeimage = QtWidgets.QLabel(Rezeptanleitung)
        self.l_recipeimage.setGeometry(QtCore.QRect(30, 140, 371, 211))
        self.l_recipeimage.setAutoFillBackground(False)
        self.l_recipeimage.setStyleSheet("\n"
"image: url(:/Images/italienischer-zitronenkuchen.jpg);")
        self.l_recipeimage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l_recipeimage.setText("")
        self.l_recipeimage.setScaledContents(True)
        self.l_recipeimage.setWordWrap(False)
        self.l_recipeimage.setObjectName("l_recipeimage")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Rezeptanleitung)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 580, 371, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.d_list = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.d_list.setObjectName("d_list")
        self.gridLayout_2.addWidget(self.d_list, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Rezeptanleitung)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(440, 580, 411, 78))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.b_addrecipe = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_addrecipe.setObjectName("b_addrecipe")
        self.horizontalLayout.addWidget(self.b_addrecipe)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)

        self.retranslateUi(Rezeptanleitung)
        QtCore.QMetaObject.connectSlotsByName(Rezeptanleitung)

    def retranslateUi(self, Rezeptanleitung):
        _translate = QtCore.QCoreApplication.translate
        Rezeptanleitung.setWindowTitle(_translate("Rezeptanleitung", "Haushaltsplaner"))
        self.l_recipe.setText(_translate("Rezeptanleitung", "\"Rezeptname\""))
        self.b_back.setText(_translate("Rezeptanleitung", "Zurück"))
        self.b_addrecipe.setText(_translate("Rezeptanleitung", "Hinzufügen"))
import menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rezeptanleitung = QtWidgets.QWidget()
    ui = Ui_Rezeptanleitung()
    ui.setupUi(Rezeptanleitung)
    Rezeptanleitung.show()
    sys.exit(app.exec_())
