# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipeframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Einkaufsplaner(object):
    def setupUi(self, Einkaufsplaner):
        Einkaufsplaner.setObjectName("Einkaufsplaner")
        Einkaufsplaner.resize(510, 564)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Einkaufsplaner)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 451, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(135, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.l_app = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_app.setStyleSheet("font-size: 15pt;")
        self.l_app.setAlignment(QtCore.Qt.AlignCenter)
        self.l_app.setObjectName("l_app")
        self.horizontalLayout_4.addWidget(self.l_app)
        self.l_icon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.l_icon.setStyleSheet("image: url(:/Images/logo_small_icon_only_inverted.png);")
        self.l_icon.setText("")
        self.l_icon.setObjectName("l_icon")
        self.horizontalLayout_4.addWidget(self.l_icon)
        self.t_recipelist = QtWidgets.QTableWidget(Einkaufsplaner)
        self.t_recipelist.setGeometry(QtCore.QRect(30, 140, 451, 271))
        self.t_recipelist.setObjectName("t_recipelist")
        self.t_recipelist.setColumnCount(0)
        self.t_recipelist.setRowCount(0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Einkaufsplaner)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 440, 451, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.b_back = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_back.setObjectName("b_back")
        self.horizontalLayout.addWidget(self.b_back)
        self.b_recipeview = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.b_recipeview.setObjectName("b_recipeview")
        self.horizontalLayout.addWidget(self.b_recipeview)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        self.retranslateUi(Einkaufsplaner)
        QtCore.QMetaObject.connectSlotsByName(Einkaufsplaner)

    def retranslateUi(self, Einkaufsplaner):
        _translate = QtCore.QCoreApplication.translate
        Einkaufsplaner.setWindowTitle(_translate("Einkaufsplaner", "Haushaltsplaner"))
        self.l_app.setText(_translate("Einkaufsplaner", "Rezepte"))
        self.b_back.setText(_translate("Einkaufsplaner", "Zurück"))
        self.b_recipeview.setText(_translate("Einkaufsplaner", "Rezept ansehen"))
import menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Einkaufsplaner = QtWidgets.QWidget()
    ui = Ui_Einkaufsplaner()
    ui.setupUi(Einkaufsplaner)
    Einkaufsplaner.show()
    sys.exit(app.exec_())
