# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(681, 578)
        self.formLayoutWidget = QtWidgets.QWidget(Login)
        self.formLayoutWidget.setGeometry(QtCore.QRect(190, 310, 311, 52))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_username = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_username.setObjectName("label_username")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_username)
        self.user_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.user_edit.setObjectName("user_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_edit)
        self.label_password = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.pass_edit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pass_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_edit.setObjectName("pass_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pass_edit)
        self.gridLayoutWidget = QtWidgets.QWidget(Login)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 370, 311, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.login_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.login_button.setObjectName("login_button")
        self.gridLayout.addWidget(self.login_button, 0, 0, 1, 1)
        self.register_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.register_button.setObjectName("register_button")
        self.gridLayout.addWidget(self.register_button, 0, 1, 1, 1)
        self.Logo = QtWidgets.QLabel(Login)
        self.Logo.setGeometry(QtCore.QRect(150, 80, 401, 201))
        self.Logo.setStyleSheet("image: url(:/newPrefix/logo_large.png);")
        self.Logo.setText("")
        self.Logo.setObjectName("Logo")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Haushaltsplaner"))
        self.label_username.setText(_translate("Login", "Username"))
        self.label_password.setText(_translate("Login", "Password"))
        self.login_button.setText(_translate("Login", "Login"))
        self.register_button.setText(_translate("Login", "Register"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
